name: build-docker
description: 'Builds docker image and pushes to github registry'
branding:
  icon: 'globe'
  color: 'white'

inputs:
  REGISTRY_TOKEN:
    description: 'for registry'
    required: true
  REGISTRY:
    description: 'registry'
    default: 'ghcr.io'
    required: true
  IMAGE_NAME:
    description: 'name of image'
    required: true
  DOCKERFILE:
    description: 'path to Dockerfile'
    default: 'Dockerfile'
    required: true
  VERSION:
    description: 'version of image'
    required: true

runs:
  using: 'composite'

  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # https://github.com/docker/login-action
    - name: Log into registry ${{ inputs.REGISTRY }}
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ inputs.REGISTRY_TOKEN }}

    - name: Build and push Docker image
      id: build-and-push
      shell: bash
      run: |
        docker build \
          -f ${{ inputs.DOCKERFILE }} \
          -t ${{ inputs.REGISTRY }}/${{ inputs.IMAGE_NAME }}:${{ inputs.VERSION }} .
        docker push ${{ inputs.REGISTRY }}/${{ inputs.IMAGE_NAME }}:${{ inputs.VERSION }}
