export const Command = {
  BALANCE: 'balance',
  BUY_GAS: 'buy_gas',
  ['BUYTOKEN_0.05']: 'buytoken_0.05',
  ['BUYTOKEN_0.06']: 'buytoken_0.06',
  ['BUYTOKEN_0.08']: 'buytoken_0.08',
  ['BUYTOKEN_0.1']: 'buytoken_0.1',
  ['BUYTOKEN_0.11']: 'buytoken_0.11',
  ['BUYTOKEN_0.12']: 'buytoken_0.12',
  ['BUYTOKEN_0.15']: 'buytoken_0.15',
  ['BUYTOKEN_0.25']: 'buytoken_0.25',
  BUYTOKEN_CUSTOM: 'buytoken_custom',
  CANCEL: 'cancel',
  CREATE_WALLET: 'create_wallet',
  DISMISS_MESSAGE: 'dismiss_message',
  DUMMY: 'dummy',
  IMPORT_WALLET: 'import_wallet',
  JITO_TIP: 'jito_tip',
  REFRESH: 'refresh',
  SELL_GAS: 'sell_gas',
  ['SELLTOKEN_50']: 'selltoken_50',
  ['SELLTOKEN_100']: 'selltoken_100',
  ['SELLTOKEN_X']: 'selltoken_x',
  SLIPPAGE: 'slippage',
};
