export const Command = {
  BALANCE: 'balance',
  BUY_GAS: 'buy_gas',
  ['BUYTOKEN_0.01']: 'buytoken_0.01',
  ['BUYTOKEN_0.05']: 'buytoken_0.05',
  ['BUYTOKEN_0.1']: 'buytoken_0.1',
  ['BUYTOKEN_0.25']: 'buytoken_0.25',
  ['BUYTOKEN_0.5']: 'buytoken_0.5',
  BUYTOKEN_CUSTOM: 'buytoken_custom',
  CANCEL: 'cancel',
  DISMISS_MESSAGE: 'dismiss_message',
  DUMMY: 'dummy',
  JITO_TIP: 'jito_tip',
  REFRESH: 'refresh',
  SELL_GAS: 'sell_gas',
  ['SELLTOKEN_50']: 'selltoken_50',
  ['SELLTOKEN_100']: 'selltoken_100',
  ['SELLTOKEN_X']: 'selltoken_x',
  SLIPPAGE: 'slippage',
};
