export const Command = {
  APPROVE_TOKEN: 'approve_token',
  BALANCE: 'balance',
  BUY_GAS: 'buy_gas',
  ['BUYTOKEN_0.03']: 'buytoken_0.03',
  ['BUYTOKEN_0.04']: 'buytoken_0.04',
  ['BUYTOKEN_0.05']: 'buytoken_0.05',
  ['BUYTOKEN_0.06']: 'buytoken_0.06',
  ['BUYTOKEN_0.07']: 'buytoken_0.07',
  ['BUYTOKEN_0.08']: 'buytoken_0.08',
  ['BUYTOKEN_0.1']: 'buytoken_0.1',
  ['BUYTOKEN_0.12']: 'buytoken_0.12',
  BUYTOKEN_CUSTOM: 'buytoken_custom',
  CANCEL: 'cancel',
  CREATE_WALLET: 'create_wallet',
  DELETE_WALLET: 'delete_wallet',
  DISMISS_MESSAGE: 'dismiss_message',
  DUMMY: 'dummy',
  IMPORT_WALLET: 'import_wallet',
  JITO_TIP: 'jito_tip',
  REFRESH: 'refresh',
  SELL_GAS: 'sell_gas',
  ['SELLTOKEN_50']: 'selltoken_50',
  ['SELLTOKEN_100']: 'selltoken_100',
  ['SELLTOKEN_X']: 'selltoken_x',
  SLIPPAGE: 'slippage',
};
