export const BUYTOKEN_CUSTOM_SCENE = 'BUYTOKEN_CUSTOM_SCENE';
export const SELLTOKEN_CUSTOM_SCENE = 'SELLTOKEN_CUSTOM_SCENE';
export const SET_MAIN_WALLET_SCENE = 'SET_MAIN_WALLET_SCENE';
export const SET_SLIPPAGE_SCENE = 'SET_SLIPPAGE_SCENE';
export const WALLET_SETTINGS_SCENE = 'WALLET_SETTINGS_SCENE';
