name: Update Version
description: Increment version name and set a new tag with it.

runs:
  using: 'composite'
  steps:
    - name: Get version
      shell: bash
      run: |
        echo "Get version"
        tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
        echo "tag=$tag" >> $GITHUB_ENV
        echo "Tag obtained: $tag"

    - name: Increment Version
      shell: bash
      id: increment-version
      run: |
        major=$(echo $tag | cut -d. -f1 | sed 's/v//')
        minor=$(echo $tag | cut -d. -f2)
        patch=$(echo $tag | cut -d. -f3)

        # Ensure values are valid (fallback to 0)
        major=${major:-0}
        minor=${minor:-0}
        patch=${patch:-0}

        new_patch=$((patch + 1))
        new_tag="v${major}.${minor}.${new_patch}"

        echo "new_tag=$new_tag" >> $GITHUB_ENV
        echo "New Tag: $new_tag"

    - name: Push New Tag
      shell: bash
      id: push-new-tag
      run: |
        git tag $new_tag
        echo "New tag created: $new_tag"
        git push origin $new_tag
