export enum SceneEnum {
  BUYTOKEN_CUSTOM_SCENE = 'BUYTOKEN_CUSTOM_SCENE',
  DELETE_WALLET_SCENE = 'DELETE_WALLET_SCENE',
  MAIN_SCENE = 'MAIN_SCENE',
  SELLTOKEN_CUSTOM_SCENE = 'SELLTOKEN_CUSTOM_SCENE',
  SET_MAIN_WALLET_SCENE = 'SET_MAIN_WALLET_SCENE',
  SET_SLIPPAGE_SCENE = 'SET_SLIPPAGE_SCENE',
  WALLET_SETTINGS_SCENE = 'WALLET_SETTINGS_SCENE',
}
