export enum SceneEnum {
  TOKEN_SETTINGS_SCENE = 'TOKEN_SETTINGS_SCENE',
  DELETE_WALLET_SCENE = 'DELETE_WALLET_SCENE',
  MAIN_SCENE = 'MAIN_SCENE',
  SET_MAIN_WALLET_SCENE = 'SET_MAIN_WALLET_SCENE',
  SETUP_WALLET_SCENE = 'SETUP_WALLET_SCENE',
  WALLET_SETTINGS_SCENE = 'WALLET_SETTINGS_SCENE',
}
